### ISSUE TITLE
Trailing '-' on version with snapshot and dirtyMarker set to ""

### ISSUE THREAD

**Issue by bellini-ea** [ilovemilk/semver-git-plugin#34] opened 2020-07-14 00:57 UTC
### Given and a dirty unstage change in a branch or master, etc
![image](https://user-images.githubusercontent.com/46908694/87368277-159f0080-c532-11ea-81e8-f239bdfbe201.png)

### Results in
Note the trailing -
![image](https://user-images.githubusercontent.com/46908694/87368292-22235900-c532-11ea-96ff-6e6c12fd5b56.png)

Also curious why the version is 0.0.1 when the configuration says initial version is 0.1.0?  (note I have no tags at this point and so trying to get things going to understand the plugin better)

**Comment by ilovemilk** [comment] 2020-07-14 09:52
Thanks for reporting this issue.

The hyphen at the end if the dirty marker is bug and will be fixed with the linked PR.

The version should be 0.1.0 there is no reason why it should be 0.0.1. I also couldn't reproduce this problem with my tests.
Without a tag the initial version is defined by initialVersion if this is not defined the default is 0.1.0.

**Closed** 2020-07-15 08:24 UTC
Labels: bug
